# coding=utf-8
"""
Django settings for wangyang project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import djcelery

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cgxt57p&xb1*t3ih9&nc9j7k7l33(2bxqsfkvk(00ot63g14^&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gunicorn',
    'djcelery',
    'common',
    'lm',
    'weixin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'common.middleware.message.AdminOnlyMessageMiddleware',
    'common.middleware.visit.VisitCount',
)

ROOT_URLCONF = 'wangyang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wangyang.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wangyang',
        'USER': 'root',
        'PASSWORD': 'mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# #collect目录
# STATIC_ROOT = '/static'

ERROR = {
    'SUCC': {'code': '10000', 'msg': u'成功'},
    'ERROR': {'code': '10001', 'msg': u'未知错误'},
    'PARA_ERR': {'code': '10002', 'msg': u'表单参数错误'},
    'NOT_EXIST_ERR': {'code': '10003', 'msg': u'记录不存在'},
    'PERM_ERR': {'code': '10004', 'msg': u'没有权限进行该操作'},
    'SYS_ERR': {'code': '10005', 'msg': u'系统繁忙'},
    'EXIST_ERR': {'code': '10006', 'msg': u'记录已存在'},
    'FORBIDDEN': {'code': '10007', 'msg': u'被禁止'},
    'MAINTAINANCE': {'code': '10008', 'msg': u'功能维护'},
    'FORBIDDEN_WORD_ERR': {'code': '10010', 'msg': u'内容中包含敏感词'},
    'STATE_ERR': {'code': '10011', 'msg': u'状态错误'},
    'VERIFYCODE_ERR': {'code': '10012', 'msg': u'验证码错误'},
    'OVERFLOW_MAX_LENGTH_ERR': {'code': '10014', 'msg': u'超出内容长度限制'},
    'UNSUPPORT_ERR': {'code': '10016', 'msg': u'不支持该功能'},
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "127.0.0.1:6379:1",
        'TIMEOUT': 60,
        "OPTIONS": {
            "PASSWORD": "redis",
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

djcelery.setup_loader()
BROKER_URL = 'redis://:redis@127.0.0.1:6379/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_IGNORE_RESULT = True